### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by docfactory37** [digrouz/docker-transmission#1]
Hi digrouz,

im just trying to build your image and im just getting the error below, was hope you may be able to help / point me in the write direction on fixing it?

base image im using is 3.16.3
transmission version 3.0.0

it used to build with no issue but now it just wont, i also try the latest code in your repo but i get the same issue.

![image](https://user-images.githubusercontent.com/20963053/216906176-ba8ce10c-397e-4ada-9022-5225192a807a.png)

**Comment by digrouz** [comment]
Hi,

Thanks for reporting this issue.

This error means downloaded tar is wrong. Might be several causes, but i can reproduce it. Sounds like the download url i was using is deprecated from github. 

My current master holds working version.  I you want to stay in 3.16.3, just update your curl url.

I might soon rework this container and release a new version with s6-overlay and some telegram notification script.

Kind Regards

**Comment by docfactory37** [comment]
Thank you for your help that's what I thought with the url, I will have a look at it tomorrow.

Thank you for the quick reply 😊
